stages:
  - deploy

before_script:
  - hostname
  - whoami
# - pwd

deploy-database-txt:
  stage: deploy
  tags:
    - linux
  artifacts:
     name: database
     when: always
     paths:
      - database.txt
  script:
    - ./.ci/deploy-database-txt.sh . database.txt

deploy-database-json:
  stage: deploy
  tags:
    - linux
    - python3
  artifacts:
     name: database
     when: always
     paths:
      - database.json
  script:
    - ./.ci/deploy-database-json.py --refs-path ./ --output database.json --nice-json 1
